fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    mkdir: "https://github.com/flypenguin/puppet-mkdir.git"
    staging: "https://github.com/voxpupuli/puppet-staging.git"
    supervisord: "https://github.com/ajcrowe/puppet-supervisord.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"

  symlinks:
    talend_commandline: "#{source_dir}"
